# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: placeholder_default

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: es

pipeline:
    - name: SpacyNLP
        model: es_core_news_md
    - name: SpacyTokenizer
    - name: SpacyFeaturizer
    - name: LanguageModelFeaturizer
        model_name: "bert"
        model_weights: "rasa/LaBSE"
    - name: DIETClassifier
        epochs: 100
        learning_rate: 0.001

policies:
    - name: MemoizationPolicy
    - name: TEDPolicy
        max_history: 5
        epochs: 100